# Generated by Django 3.2.8 on 2022-02-25 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
                ('apellido', models.CharField(default='', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Jueces',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Adopcion', 'Adopcion'), ('Alimentos $500.000 (prueba conforme estándares mínimos)', 'Alimentos $500.000 (prueba conforme estándares mínimos)'), ('Alimentos $500.000', 'Alimentos $500.000'), ('Alimentos > M$ 500.000 (y abundante prueba)', 'Alimentos > M$ 500.000 (y abundante prueba)'), ('Alimentos, Aumento ', 'Alimentos, Aumento '), ('Alimentos, Cesación', 'Alimentos, Cesación'), ('Alimentos, Otros', 'Alimentos, Otros'), ('Alimentos, Rebaja', 'Alimentos, Rebaja'), ('Autorización Para Enajenar Bienes Raíces', 'Autorización Para Enajenar Bienes Raíces'), ('Autorización Salida Del País Definido CON oposición', 'Autorización Salida Del País Definido CON oposición'), ('Autorización Salida Del País Definida SIN oposición', 'Autorización Salida Del País Definida SIN oposición'), ('Autorización Salida Del País Indefinida con oposición', 'Autorización Salida Del País Indefinida con oposición'), ('Cuidado Personal Del Niño', 'Cuidado Personal Del Niño'), ('Declaración De Bienes Familiares SIN/oposición', 'Declaración De Bienes Familiares SIN/oposición'), ('Declaración De Bienes Familiares CON/oposición', 'Declaración De Bienes Familiares CON/oposición'), ('Declaración De Susceptibilidad CON/oposición', 'Declaración De Susceptibilidad CON/oposición'), ('Declaración De Susceptibilidad SIN/oposición', 'Declaración De Susceptibilidad SIN/oposición'), ('Divorcio c/oposición', 'Divorcio c/oposición'), ('Divorcio De Común Acuerdo CON abogado particular', 'Divorcio De Común Acuerdo CON abogado particular'), ('Divorcio De Común Acuerdo SIN abogado particular', 'Divorcio De Común Acuerdo SIN abogado particular'), ('Divorcio simple', 'Divorcio simple'), ('Guardador Menores De Edad, Nombramiento', 'Guardador Menores De Edad, Nombramiento'), ('Infracción A La Ley Penal', 'Infracción A La Ley Penal'), ('Maternidad, Impugnación Y Reconocimiento CON/oposición', 'Maternidad, Impugnación Y Reconocimiento CON/oposición'), ('Maternidad, Impugnación Y Reconocimiento SIN/oposición', 'Maternidad, Impugnación Y Reconocimiento SIN/oposición'), ('Nulidad Matrimonial', 'Nulidad Matrimonial'), ('Otros Asuntos De Tramitación Ordinaria o con multiplicidad', 'Otros Asuntos De Tramitación Ordinaria o con multiplicidad'), ('Paternidad, Impugnación De', 'Paternidad, Impugnación De'), ('Paternidad, Impugnación Y Reconocimiento De CON/oposición', 'Paternidad, Impugnación Y Reconocimiento De CON/oposición'), ('Paternidad, Impugnación Y Reconocimiento De SIN/oposición', 'Paternidad, Impugnación Y Reconocimiento De SIN/oposición'), ('Paternidad, Investigación De', 'Paternidad, Investigación De'), ('Paternidad, Reconocimiento De', 'Paternidad, Reconocimiento De'), ('Patria Potestad, Suspensión', 'Patria Potestad, Suspensión'), ('Relación Directa Y Regular Con El Niño CON/oposición', 'Relación Directa Y Regular Con El Niño CON/oposición'), ('Relación Directa Y Regular Con El Niño SIN/oposición', 'Relación Directa Y Regular Con El Niño SIN/oposición'), ('Relación Directa Y Regular Modificación', 'Relación Directa Y Regular Modificación'), ('Relación Directa Y Regular Suspensión', 'Relación Directa Y Regular Suspensión'), ('Separación Judicial De Bienes', 'Separación Judicial De Bienes'), ('Separación Matrimonial', 'Separación Matrimonial'), ('Secuestro internacional', 'Secuestro internacional'), ('Violencia Intrafamiliar CON/ abogado', 'Violencia Intrafamiliar CON/ abogado'), ('Violencia Intrafamiliar SIN/ abogado', 'Violencia Intrafamiliar SIN/ abogado'), ('VULNERACIÓN DE DERECHOS SIMPLE', 'VULNERACIÓN DE DERECHOS SIMPLE'), ('Vulneración De Derechos Compleja (DAM)', 'Vulneración De Derechos Compleja (DAM)'), ('Causas con multiplicidad de materias ', 'Causas con multiplicidad de materias')], max_length=200)),
                ('tipologia', models.CharField(choices=[('SIN COMPLEJIDAD', 'SIN COMPLEJIDAD'), ('COMPLEJA', 'COMPLEJA'), ('ABOGADO PARTICULAR', 'ABOGADO PARTICULAR'), ('ABOGADO CAJ', 'ABOGADO CAJ'), ('ESPECIALIZADA', 'ESPECIALIZADA')], max_length=30)),
                ('tiempo_preparatoria', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=20)),
                ('tiempo_juicio', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('NO', 'NO')], default='-', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RevisionPost',
            fields=[
                ('preguntas', models.BooleanField(blank=True, default=False, primary_key=True, serialize=False, verbose_name='preguntas')),
            ],
        ),
        migrations.CreateModel(
            name='Rit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(choices=[('V', 'V'), ('W', 'W'), ('R', 'R'), ('P', 'P'), ('I', 'I'), ('M', 'M'), ('A', 'A'), ('C', 'C'), ('T', 'T'), ('X', 'X'), ('Z', 'Z'), ('E', 'E'), ('F', 'F'), ('S', 'S')], max_length=2, verbose_name='letra')),
                ('nro_causa', models.CharField(blank=True, max_length=8, verbose_name='Numero de la causa')),
                ('anio', models.CharField(max_length=4, verbose_name='Año')),
            ],
        ),
        migrations.CreateModel(
            name='Audiencia',
            fields=[
                ('rit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apps.rit', verbose_name='Rit de la causa')),
                ('fecha_audiencia', models.DateField(blank=True, verbose_name='Fecha a solicitar')),
                ('fecha_fin_audiencia', models.DateField(blank=True, null=True)),
                ('hora_audiencia', models.TimeField(blank=True, verbose_name='Hora audiencia')),
                ('cant_bloques', models.PositiveIntegerField(default=1, verbose_name='Bloques')),
                ('tipo_audiencia', models.CharField(blank=True, choices=[('Preparatoria', 'Preparatoria'), ('Juicio', 'Juicio'), ('Continuacion preparatoria', 'Continuacion preparatoria'), ('Continuacion juicio', 'Continuacion juicio'), ('Especial', 'Especial'), ('Continuacion especial', 'Continuacion especial'), ('Otras continuaciones', 'Otras continuaciones')], default='-', max_length=50, verbose_name='Tipo de audiencia')),
                ('notificacion_exhorto', models.BooleanField(blank=True, default=False, verbose_name='Requiere notificacion exhorto')),
                ('parte_recluida', models.BooleanField(blank=True, default=False, verbose_name='Alguna parte esta recluida')),
                ('parte_santa_maria', models.BooleanField(blank=True, default=False, verbose_name='Alguna parte reside en la Isla Santa Maria')),
                ('audiencia_reservada', models.BooleanField(blank=True, default=False, verbose_name='La audiencia se encuentra reservada')),
                ('audiencia_interprete', models.BooleanField(blank=True, default=False, verbose_name='La audiencia requiere interprete')),
                ('abogado_curador', models.CharField(blank=True, default='-', max_length=100, verbose_name='Nombre abogado o Institucion')),
                ('existen_diligencias', models.CharField(blank=True, choices=[('Documental', 'Documental'), ('Testimonial', 'Testimonial'), ('Pericial', 'Pericial')], default='-', max_length=30)),
                ('reservada_gesell', models.BooleanField(blank=True, default=False, verbose_name='Audiencia reservada Gesell')),
                ('adm_sala', models.CharField(blank=True, default='-', max_length=5)),
                ('cant_asistentes', models.IntegerField(blank=True, default=0)),
                ('a_publico', models.CharField(blank=True, default='-', max_length=10)),
                ('realizacion', models.CharField(blank=True, choices=[('REALIZADA', 'Audiencia realizada'), ('NO REALIZADA', 'Audiencia no realizada'), ('SUSPENDIDA', 'Audiencia suspendida')], default='-', max_length=30)),
                ('tipo_motivo', models.CharField(blank=True, choices=[('CUMPLE', 'Cumple lo ordenado'), ('FECHA', 'Cambio de fecha')], default='-', max_length=30)),
                ('ambasPartes_renuncian', models.BooleanField(blank=True, default=False)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('fecha_ingreso_causa', models.DateField(blank=True, null=True)),
                ('sala', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='-', max_length=2)),
                ('fecha_nuevaAudiencia', models.DateField(blank=True, null=True, verbose_name='Fecha de la nueva audiencia')),
                ('hora_nuevaAudiencia', models.TimeField(blank=True, null=True, verbose_name='Hora de la nueva audiencia')),
                ('solicitante', models.CharField(default='S/S', max_length=60)),
                ('juez', models.ForeignKey(blank=True, default='Sin Juez', on_delete=django.db.models.deletion.CASCADE, to='apps.juez', verbose_name='Juez asignado')),
                ('materia', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apps.materia')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAudiencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_audiencia', models.DateField(blank=True, verbose_name='Fecha a solicitar')),
                ('hora_audiencia', models.TimeField(blank=True, verbose_name='Hora audiencia')),
                ('cant_bloques', models.PositiveIntegerField(default=1, verbose_name='Bloques')),
                ('abogado_curador', models.CharField(blank=True, default='-', max_length=100, verbose_name='Nombre abogado o Institucion')),
                ('tipo_audiencia', models.CharField(blank=True, choices=[('Preparatoria', 'Preparatoria'), ('Juicio', 'Juicio'), ('Continuacion preparatoria', 'Continuacion preparatoria'), ('Continuacion juicio', 'Continuacion juicio'), ('Especial', 'Especial'), ('Continuacion especial', 'Continuacion especial'), ('Otras continuaciones', 'Otras continuaciones')], default='-', max_length=50, verbose_name='Tipo de audiencia')),
                ('notificacion_exhorto', models.BooleanField(blank=True, default=False, verbose_name='Requiere notificacion exhorto')),
                ('parte_recluida', models.BooleanField(blank=True, default=False, verbose_name='Alguna parte esta recluida')),
                ('parte_santa_maria', models.BooleanField(blank=True, default=False, verbose_name='Alguna parte reside en la Isla Santa Maria')),
                ('audiencia_reservada', models.BooleanField(blank=True, default=False, verbose_name='La audiencia se encuentra reservada')),
                ('audiencia_interprete', models.BooleanField(blank=True, default=False, verbose_name='La audiencia requiere interprete')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Ingresada', 'Ingresada')], default='Pendiente', max_length=10, verbose_name='Estado de la solicitud')),
                ('juez', models.ForeignKey(blank=True, default='Sin Juez', on_delete=django.db.models.deletion.CASCADE, to='apps.juez', verbose_name='Juez asignado')),
                ('materia', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apps.materia')),
                ('rit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apps.rit', verbose_name='Rit de la causa')),
            ],
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('audiencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apps.audiencia')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadRevision',
            fields=[
                ('rit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apps.audiencia')),
                ('estado_causa_SITFA', models.BooleanField(blank=True, default=False)),
                ('existe_abogado_registrado', models.BooleanField(blank=True, default=False)),
                ('nombres_partes', models.BooleanField(blank=True, default=False)),
                ('rut_ingresado_SITFA', models.BooleanField(blank=True, default=False)),
                ('correos_partes_ingresados', models.BooleanField(blank=True, default=False)),
                ('acta_en_plazo', models.BooleanField(blank=True, default=False)),
                ('tramitacion_refleja_audiencia', models.BooleanField(blank=True, default=False)),
                ('acta_corresponde_formato', models.BooleanField(blank=True, default=False)),
                ('notificaciones_SITFA', models.BooleanField(blank=True, default=False)),
                ('causasVIF_remite_oficio', models.BooleanField(blank=True, default=False)),
                ('estandar_minimo_prueba', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
